export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL= 'GET_POSTS_FAIL';

export const UPDATE_POSTS_START = 'UPDATE_POSTS_START';
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS';
export const UPDATE_POSTS_FAIL= 'UPDATE_POSTS_FAIL';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USERS_BY_ID_START = 'GET_USERS_BY_ID_START';
export const GET_USERS_BY_ID_SUCCESS = 'GET_USERS_BY_ID_SUCCESS';
export const GET_USERS_BY_ID_FAIL = 'GET_USERS_BY_ID_FAIL';